# Zakomentujeme celý soubor nebo přejmenujeme na test.yml.disabled
name: Backend Tests
# on:
#   push:
#     branches: [ main ]
#     paths:
#       - 'backend/**'
#   pull_request:
#     branches: [ main ]
#     paths:
#       - 'backend/**'
# 
# jobs:
#   test:
#     runs-on: ubuntu-latest
#     ... 